example:
  fullname: test-server

  labels:
    app: test-server-app

  selectorLabels:
    app: test-server-app
    nodes: frontend

  serviceAccountName: private

image:
  name: bjd2385/private-httpd-mod
  tag: "" # grab latest
  pullPolicy: Always

resources: {}
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi