example:
  fullname: test-server

labels:
  app: test-server-app
  nodes: frontend

selectorLabels:
  nodes: frontend

  # Because this is only an example, and not an actual production case, I've modded the default ns.
  serviceAccountName: default

image:
  name: bjd2385/private-httpd-mod
  tag: "" # grab latest
  pullPolicy: Always
  secretName: personal-docker-private

resources: {}
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi