apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example.fullname" . }}
  labels:
{{- toYaml .Values.example.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- toYaml .Values.example.selectorLabels | nindent 6 }}
  template:
    metadata:
    spec:
      serviceAccountName: {{ .Values.example.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          # Modifying the following lines to ensure the cluster pulls secrets to access a private repository on Docker Hub.
          # Repository hosts the exact same container image as bjd2385/httpd, from website/Dockerfile in this repository.
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 443
          readinessProbe:
            tcpSocket:
              port: 443
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 8 }}
{{ else }}
          # Set default resource constraints to ensure the mem leak doesn't take over the entire node.
          resources:
            limits:
              cpu: 500m
              mem: 500Mi
            requests:
              cpu: 200m
              mem: 200Mi
{{ end }}